name: â™»ï¸ Reusable - ðŸ” Find Updated Dockerfiles and Create Matrix
on:
  workflow_call:
    inputs:
      base_folder:
        required: true
        type: string
      artifact_name:
        required: true
        type: string
jobs:
  find-dockerfiles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # Step to checkout the repository

      # Step to find Dockerfiles in the specified base folder that have been updated
      - name: Find updated Dockerfiles
        id: find
        run: |
          git fetch origin main
          git diff --name-only origin/main | grep -E '^${{ inputs.base_folder }}/.*/Dockerfile$' | sed 's/\/Dockerfile//' | sed 's/^/.\//' > updated_dockerfile_paths.txt
          cat updated_dockerfile_paths.txt
          # This command finds all Dockerfiles in the specified base folder,
          # modifies the paths, and stores them in dockerfile_paths.txt

      # Step to create a JSON matrix from the found Dockerfile paths
      - name: Create JSON matrix
        id: generate-matrix
        run: |
          jq -R . < updated_dockerfile_paths.txt | jq -s . > dockerfile_paths.json
          cat dockerfile_paths.json
          # This command converts the paths in dockerfile_paths.txt to a JSON array
          # and saves it as dockerfile_paths.json

      # Step to upload the JSON matrix as an artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: dockerfile_paths.json
          # This uploads dockerfile_paths.json as an artifact named based on the input